version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    groups:
      python-development:
        patterns: ["*"]
  - package-ecosystem: terraform
    directory: "/infra/azure"
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: "/infra/databricks"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
